### ISSUE TITLE
vscode TS language server fails to detect references

### ISSUE THREAD

**Issue by nopeless** [ahoopen/typescript-mono-repo#11]
fresh clone of master

**Comment by nopeless** [comment]
Additional context: 

```
npx tsc -b                              
packages/web/src/add.ts:1:31 - error TS2307: Cannot find module '@ahoopen/utils' or its corresponding type declarations.

1 import { multiplyByTwo } from "@ahoopen/utils";
                                ~~~~~~~~~~~~~~~~


Found 1 error.
```

**Comment by ahoopen** [comment]
Hi @nopeless ,

The package is an example. It's not published on the NPM registry. It was only used to illustrate the usage.

**Comment by nopeless** [comment]
@ahoopen I belive you are mistaken. That is your project. Your project fails to compile out of the box

**Comment by ahoopen** [comment]
Thanks for the feedback! I have fixed the issue: https://github.com/ahoopen/typescript-mono-repo/pull/14
