### ISSUE TITLE
Monorepo not worked: Cannot find module '@ahoopen/utils' 

### ISSUE THREAD

**Issue by whalemare** [ahoopen/typescript-mono-repo#7]
```
git clone https://github.com/ahoopen/typescript-mono-repo
yarn
yarn build
```

```
yarn run v1.22.10
$ lerna run build --stream
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 3 packages: "yarn run build"
@ahoopen/utils: $ yarn clean && tsc --build && cp "./package.json" ./dist/
@ahoopen/core: $ yarn clean && tsc --build && cp "./package.json" ./dist/
@ahoopen/core: $ rimraf dist && rimraf tsconfig.tsbuildinfo
@ahoopen/utils: $ rimraf dist && rimraf tsconfig.tsbuildinfo
@ahoopen/web: $ yarn clean && tsc --build && cp "./package.json" ./dist/
@ahoopen/web: $ rimraf dist && rimraf tsconfig.tsbuildinfo
@ahoopen/web: src/add.ts(1,31): error TS2307: Cannot find module '@ahoopen/utils' or its corresponding type declarations.
@ahoopen/web: error Command failed with exit code 1.
@ahoopen/web: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@ahoopen/web'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by ahoopen** [comment]
The reason is because that package doesn't exist. You should use your own packages :)
This was an example of use. Will try to find some time to update the starterkit

**Comment by deanhiller** [comment]
great blog article!!!  I am still stuck on this issue and just posted it on SO as well before realizing to look here.  (SO post: https://stackoverflow.com/questions/72194169/trying-typescript-monobuild-and-last-step-fails-following-simple-blog-article )

ohhh, uhhhhh, I am so confused.   In typescript-mono-repo/packages/utils/package.json, the name is '@ahoopen/utils' but @hoopen/web says Cannot find module '@hoopen/utils' which I thought is the utils directory but then you say the package doesn't exist?

I was going to switch all the @ahoopen over to a company name or something.  I am very confused on the final steps on making this work exactly.  Also, I am very worried about the tsconfig.json in that we have to update it every time someone adds a new library in the monorepo?  (just worried my developers may miss adding to that file every time as it grows - any way to avoid that?)

**Comment by ahoopen** [comment]
Hi @deanhiller

The reason why it is giving you this error is because the packages aren't published on the NPM registry. Perhaps i should publish the dummy packages to NPM so the repo works out of the box. 

But it was used as an example. @ahoopen is the namespace of the package, for you it would be different. Depending if you publish on Github packages or NPM.

In your situation, you have to publish all your packages under the company name / account. Hope this makes sense :) If you have any questions, please let me know

**Comment by ahoopen** [comment]
I have fixed the issue: https://github.com/ahoopen/typescript-mono-repo/pull/14
